version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: invoiceIt
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'db.runCommand({find:"invoiceIt.invoiceUser"}).ok' | mongosh --authenticationDatabase admin --host localhost -u rootuser -p rootpass admin --quiet | grep -q 1
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 20s

  backend:
    build: ./invoiceIt_backend
    volumes:
      - ./invoiceIt_backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URL: "mongodb://invoiceUser:passinvoice123@mongo:27017/invoiceIt"
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build: ./invoiceIt_frontend_react
    ports:
      - "3000:3000"
    volumes:
      - ./invoiceIt_frontend_react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo-data:
